export const ARTICLE_WRITE_REQUEST = "ARTICLE_WRITE_REQUEST";
export const ARTICLE_WRITE_SUCCESS = "ARTICLE_WRITE_SUCCESS";
export const ARTICLE_WRITE_FAIL = "ARTICLE_WRITE_FAIL";
export const ARTICLE_WRITE_RESET = "ARTICLE_WRITE_RESET";

export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_FAIL = "ARTICLE_DETAILS_FAIL";

export const ARTICLE_UPDATE_REQUEST = "ARTICLE_UPDATE_REQUEST";
export const ARTICLE_UPDATE_SUCCESS = "ARTICLE_UPDATE_SUCCESS";
export const ARTICLE_UPDATE_FAIL = "ARTICLE_UPDATE_FAIL";
export const ARTICLE_UPDATE_RESET = "ARTICLE_UPDATE_RESET";

export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";

export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";
export const ARTICLE_DELETE_FAIL = "ARTICLE_DELETE_FAIL";
export const ARTICLE_DELETE_RESET = "ARTICLE_DELETE_RESET";

export const ARTICLE_LATEST_REQUEST = "ARTICLE_LATEST_REQUEST";
export const ARTICLE_LATEST_SUCCESS = "ARTICLE_LATEST_SUCCESS";
export const ARTICLE_LATEST_FAIL = "ARTICLE_LATEST_FAIL";

export const ARTICLE_RELATED_REQUEST = "ARTICLE_RELATED_REQUEST";
export const ARTICLE_RELATED_SUCCESS = "ARTICLE_RELATED_SUCCESS";
export const ARTICLE_RELATED_FAIL = "ARTICLE_RELATED_FAIL";

export const ARTICLE_NOT_RELATED_REQUEST = "ARTICLE_NOT_RELATED_REQUEST";
export const ARTICLE_NOT_RELATED_SUCCESS = "ARTICLE_NOT_RELATED_SUCCESS";
export const ARTICLE_NOT_RELATED_FAIL = "ARTICLE_NOT_RELATED_FAIL";
