export const SUGGESTION_WRITE_REQUEST = "SUGGESTION_WRITE_REQUEST";
export const SUGGESTION_WRITE_SUCCESS = "SUGGESTION_WRITE_SUCCESS";
export const SUGGESTION_WRITE_FAIL = "SUGGESTION_WRITE_FAIL";
export const SUGGESTION_WRITE_RESET = "SUGGESTION_WRITE_RESET";

export const SUGGESTIONS_LIST_REQUEST = "SUGGESTIONS_LIST_REQUEST";
export const SUGGESTIONS_LIST_SUCCESS = "SUGGESTIONS_LIST_SUCCESS";
export const SUGGESTIONS_LIST_FAIL = "SUGGESTIONS_LIST_FAIL";

export const SUGGESTION_UPDATE_REQUEST = "SUGGESTION_UPDATE_REQUEST";
export const SUGGESTION_UPDATE_SUCCESS = "SUGGESTION_UPDATE_SUCCESS";
export const SUGGESTION_UPDATE_FAIL = "SUGGESTION_UPDATE_FAIL";
export const SUGGESTION_UPDATE_RESET = "SUGGESTION_UPDATE_RESET";
