export const TRAINING_SCHEDULE_CREATE_REQUEST =
  "TRAINING_SCHEDULE_CREATE_REQUEST";
export const TRAINING_SCHEDULE_CREATE_SUCCESS =
  "TRAINING_SCHEDULE_CREATE_SUCCESS";
export const TRAINING_SCHEDULE_CREATE_FAIL = "TRAINING_SCHEDULE_CREATE_FAIL";
export const TRAINING_SCHEDULE_CREATE_RESET = "TRAINING_SCHEDULE_CREATE_RESET";

export const TRAINING_SCHEDULE_LIST_REQUEST = "TRAINING_SCHEDULE_LIST_REQUEST";
export const TRAINING_SCHEDULE_LIST_SUCCESS = "TRAINING_SCHEDULE_LIST_SUCCESS";
export const TRAINING_SCHEDULE_LIST_FAIL = "TRAINING_SCHEDULE_LIST_FAIL";
